name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: brew bundle
      - run: xcodegen generate
      - run: xcodebuild -scheme FoxCleanApp -destination 'platform=macOS' build
      - run: swift build
